apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.namespace.name }} 
  name: {{ .Values.namespace.name }} 
  namespace: {{ .Values.namespace.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: {{ .Values.namespace.name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.namespace.name }} 
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.namespace.name }} 
        ports:
        - containerPort: {{ .Values.containerPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.containerPort }}        
        resources:
{{ toYaml .Values.resources | indent 12 }}
